import type { NextPage } from 'next'
import Head from 'next/head'
// import UseStateComp from '../components/UseStateComp'
// import UseEffectComp from '../components/useEffectComp'
import styles from '../styles/Home.module.css'
import UseContextComp from '../components/UseContextComp'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 className='text-5xl tracking-wide font-bold'> Typescript hooks </h1>
          {/* <UseStateComp /> */}
          {/* <UseEffectComp /> */}
          <UseContextComp />
        </div>
      </main>
    </div>
  )
}

export default Home
